<a href="https://colab.research.google.com/github/yadavrahyl2k15/Stacking/blob/main/stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [19]:
df=pd.read_csv("/content/diabetes.csv")

In [20]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [21]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [22]:
x=df.drop(columns="Outcome")

In [23]:
y=df["Outcome"]

For stacking we can divide data in more than 2 times between train and test

In [24]:
train,val_train,test,val_test=train_test_split(x,y,test_size=0.5,random_state=50)

In [25]:
x_train,x_test,y_train,y_test=train_test_split(train,test,test_size=0.2,random_state=20)

In [26]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
svm=SVC()
svm.fit(x_train,y_train)

SVC()

In [28]:
predict_val_1=knn.predict(val_train)

In [29]:
predict_val_2=svm.predict(val_train)

In [31]:
pred_value=np.column_stack((predict_val_1,predict_val_2))

In [32]:
rand_clf=RandomForestClassifier()
rand_clf.fit(pred_value,val_test)

RandomForestClassifier()

In [34]:
pred_test_1=knn.predict(x_test)

In [35]:
pred_test_2=svm.predict(x_test)

In [36]:
pred_test=np.column_stack((pred_test_1,pred_test_2))

In [37]:
rand_clf.predict(pred_test)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [38]:
rand_clf.score(pred_test,y_test)

0.7272727272727273

In [41]:
val_train

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
575            1      119             44  ...  35.5                     0.280   25
206            8      196             76  ...  37.5                     0.605   57
127            1      118             58  ...  33.3                     0.261   23
550            1      116             70  ...  27.4                     0.204   21
118            4       97             60  ...  28.2                     0.443   22
..           ...      ...            ...  ...   ...                       ...  ...
356            1      125             50  ...  33.3                     0.962   28
190            3      111             62  ...  22.6                     0.142   21
87             2      100             68  ...  38.5                     0.324   26
694            2       90             60  ...  23.5                     0.191   25
653            2      120             54  ...  26.8                     0.455   27

[384 rows x 8 columns]

In [42]:
knn.predict([[1,119,44,47,63,35.5,0.280,25]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

In [43]:
svm.predict([[1,119,44,47,63,35.5,0.280,25]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([0])

In [44]:
meta_x=np.column_stack((knn.predict([[1,119,44,47,63,35.5,0.280,25]]),svm.predict([[1,119,44,47,63,35.5,0.280,25]])))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


In [45]:
rand_clf.predict(meta_x)

array([0])